import { ZodiacSign } from "./types";

export const ZODIAC_SIGNS: ZodiacSign[] = [
    {
        name: "Capricorn",
        start: "12-22",
        end: "01-19",
        compatibleWith: ["Taurus", "Virgo", "Scorpio", "Pisces"],
        description: "Ambitious, disciplined, and reliable. Capricorns value tradition and hard work.",
        element: "Earth",
    },
    {
        name: "Aquarius",
        start: "01-20",
        end: "02-18",
        compatibleWith: ["Gemini", "Libra", "Sagittarius", "Aries"],
        description: "Innovative, independent, and humanitarian. Aquarians are thinkers and dreamers.",
        element: "Air",
    },
    {
        name: "Pisces",
        start: "02-19",
        end: "03-20",
        compatibleWith: ["Taurus", "Cancer", "Scorpio", "Capricorn"],
        description: "Compassionate, artistic, and intuitive. Pisces are empathetic and imaginative.",
        element: "Water",
    },
    {
        name: "Aries",
        start: "03-21",
        end: "04-19",
        compatibleWith: ["Gemini", "Leo", "Sagittarius", "Aquarius"],
        description: "Energetic, courageous, and passionate. Aries are leaders and adventurers.",
        element: "Fire",
    },
    {
        name: "Taurus",
        start: "04-20",
        end: "05-20",
        compatibleWith: ["Cancer", "Virgo", "Capricorn", "Pisces"],
        description: "Reliable, patient, and sensual. Tauruses appreciate stability and comfort.",
        element: "Earth",
    },
    {
        name: "Gemini",
        start: "05-21",
        end: "06-20",
        compatibleWith: ["Aries", "Leo", "Libra", "Aquarius"],
        description: "Versatile, communicative, and witty. Geminis are curious and adaptable.",
        element: "Air",
    },
    {
        name: "Cancer",
        start: "06-21",
        end: "07-22",
        compatibleWith: ["Taurus", "Virgo", "Scorpio", "Pisces"],
        description: "Emotional, nurturing, and intuitive. Cancers are protective and caring.",
        element: "Water",
    },
    {
        name: "Leo",
        start: "07-23",
        end: "08-22",
        compatibleWith: ["Aries", "Gemini", "Libra", "Sagittarius"],
        description: "Confident, generous, and charismatic. Leos love attention and creativity.",
        element: "Fire",
    },
    {
        name: "Virgo",
        start: "08-23",
        end: "09-22",
        compatibleWith: ["Taurus", "Cancer", "Scorpio", "Capricorn"],
        description: "Analytical, practical, and kind. Virgos are perfectionists and helpers.",
        element: "Earth",
    },
    {
        name: "Libra",
        start: "09-23",
        end: "10-22",
        compatibleWith: ["Gemini", "Leo", "Sagittarius", "Aquarius"],
        description: "Diplomatic, fair, and social. Libras seek harmony and beauty.",
        element: "Air",
    },
    {
        name: "Scorpio",
        start: "10-23",
        end: "11-21",
        compatibleWith: ["Cancer", "Virgo", "Capricorn", "Pisces"],
        description: "Passionate, resourceful, and mysterious. Scorpios are intense and loyal.",
        element: "Water",
    },
    {
        name: "Sagittarius",
        start: "11-22",
        end: "12-21",
        compatibleWith: ["Aries", "Leo", "Libra", "Aquarius"],
        description: "Optimistic, freedom-loving, and philosophical. Sagittariuses are adventurers.",
        element: "Fire",
    },
];

export const ELEMENT_COMPATIBILITY: { [key: string]: { [key: string]: number } } = {
    Fire: { Air: 85, Fire: 100, Earth: 50, Water: 40 },
    Earth: { Water: 85, Earth: 100, Air: 50, Fire: 40 },
    Air: { Fire: 85, Air: 100, Water: 50, Earth: 40 },
    Water: { Earth: 85, Water: 100, Fire: 40, Air: 50 },
};