import { CompatibilityBreakdown } from "./types";
import { getBasePath } from "./utils";

export const generateShareableLink = (
    name1: string,
    name2: string,
    gender1: string,
    gender2: string,
    dob1: string,
    dob2: string,
    result: number
): string => {
    const params = new URLSearchParams({
        n1: encodeURIComponent(name1),
        g1: gender1,
        d1: dob1,
        n2: encodeURIComponent(name2),
        g2: gender2,
        d2: dob2,
        r: result.toString(),
    });

    const basePath = getBasePath();
    return `${window.location.origin}${basePath}?${params.toString()}`;
};

export const shareResults = async (
    name1: string,
    name2: string,
    result: number,
    shareableLink: string
) => {
    const shareText = `💕 ${name1} and ${name2} are ${result}% compatible! Check our Love Calculator: ${shareableLink}`;

    if (navigator.share) {
        try {
            await navigator.share({
                title: "Love Calculator Results",
                text: shareText,
                url: shareableLink,
            });
        } catch (err) {
            console.log("Share cancelled");
        }
    }
};

export const copyToClipboard = async (
    name1: string,
    name2: string,
    result: number,
    shareableLink: string,
    setCopiedCallback: (copied: boolean) => void
) => {
    const copyText = `💕 ${name1} and ${name2} are ${result}% compatible! Check our Love Calculator: ${shareableLink}`;

    try {
        await navigator.clipboard.writeText(copyText);
        setCopiedCallback(true);
        setTimeout(() => setCopiedCallback(false), 2000);
    } catch (err) {
        console.error("Failed to copy: ", err);
        fallbackCopyTextToClipboard(copyText, setCopiedCallback);
    }
};

const fallbackCopyTextToClipboard = (text: string, setCopiedCallback: (copied: boolean) => void) => {
    const textArea = document.createElement("textarea");
    textArea.value = text;
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    try {
        document.execCommand("copy");
        setCopiedCallback(true);
        setTimeout(() => setCopiedCallback(false), 2000);
    } catch (err) {
        console.error("Fallback: Oops, unable to copy", err);
    }
    document.body.removeChild(textArea);
};

export const shareOnSocial = (
    platform: string,
    name1: string,
    name2: string,
    result: number,
    shareableLink: string
) => {
    const text = encodeURIComponent(`💕 ${name1} and ${name2} are ${result}% compatible!`);
    const url = encodeURIComponent(shareableLink);

    let shareUrl = "";

    switch (platform) {
        case "facebook":
            shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${url}&quote=${text}`;
            break;
        case "twitter":
            shareUrl = `https://twitter.com/intent/tweet?text=${text}&url=${url}`;
            break;
        case "whatsapp":
            shareUrl = `https://wa.me/?text=${text}%20${url}`;
            break;
    }

    if (shareUrl) {
        window.open(shareUrl, "_blank", "width=600,height=400");
    }
};

export const printResults = (
    name1: string,
    name2: string,
    result: number,
    message: string,
    zodiac1: string,
    zodiac2: string,
    breakdown: CompatibilityBreakdown | null
) => {
    const printContent = `
		<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; text-align: center;">
			<h1 style="color: #ff6b9d;">💕 Love Calculator Results 💕</h1>
			<h2>${name1} ❤️ ${name2}</h2>
			<h3 style="font-size: 48px; color: #ff4757;">${result}% Compatible!</h3>
			<p style="font-style: italic; margin: 20px 0;">${message}</p>
			${zodiac1 && zodiac2 ? `<p><strong>Zodiac Signs:</strong> ${zodiac1} & ${zodiac2}</p>` : ""}
			${breakdown
            ? `
				<div style="margin: 20px 0;">
					<h4>Compatibility Breakdown:</h4>
					<p>Names: ${breakdown.name}% | Age: ${breakdown.age}% | Zodiac: ${breakdown.zodiac}% | Element: ${breakdown.element}% | Magic: ${breakdown.random}%</p>
				</div>
			`
            : ""
        }
			<p style="margin-top: 30px; font-size: 12px; color: #666;">Generated by Love Calculator</p>
			<p style="font-size: 10px; color: #999;">© ${new Date().getFullYear()} Love Calculator. For entertainment purposes only.</p>
		</div>
	`;

    const printWindow = window.open("", "_blank");
    if (printWindow) {
        printWindow.document.write(printContent);
        printWindow.document.close();
        printWindow.print();
    }
};

export const downloadResults = (
    name1: string,
    name2: string,
    result: number,
    zodiac1: string,
    zodiac2: string
) => {
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    canvas.width = 800;
    canvas.height = 600;

    const gradient = ctx.createLinearGradient(0, 0, 800, 600);
    gradient.addColorStop(0, "#ff6b9d");
    gradient.addColorStop(0.5, "#c44569");
    gradient.addColorStop(1, "#6c5ce7");

    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 800, 600);

    ctx.fillStyle = "rgba(255, 255, 255, 0.1)";
    for (let i = 0; i < 50; i++) {
        const x = Math.random() * 800;
        const y = Math.random() * 600;
        const size = Math.random() * 20 + 5;
        ctx.font = `${size}px Arial`;
        ctx.fillText("💖", x, y);
    }

    ctx.fillStyle = "white";
    ctx.textAlign = "center";
    ctx.font = "bold 48px Arial";
    ctx.fillText("Love Calculator", 400, 80);

    ctx.font = "bold 36px Arial";
    ctx.fillText(`${name1} ❤️ ${name2}`, 400, 140);

    ctx.font = "bold 72px Arial";
    ctx.fillText(`${result}%`, 400, 220);

    ctx.font = "24px Arial";
    ctx.fillText("Compatible!", 400, 260);

    if (zodiac1 && zodiac2) {
        ctx.font = "18px Arial";
        ctx.fillText(`Zodiac: ${zodiac1} & ${zodiac2}`, 400, 300);
    }

    ctx.font = "14px Arial";
    ctx.fillText("Generated by Love Calculator", 400, 540);
    ctx.font = "12px Arial";
    ctx.fillText(`© ${new Date().getFullYear()} - For entertainment only`, 400, 560);

    const link = document.createElement("a");
    link.download = `love-calculator-${name1}-${name2}.png`;
    link.href = canvas.toDataURL();
    link.click();
};