name: Deploy Next.js site to Pages

on:
  push:
    branches: ["next"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore cache
        uses: actions/cache@v5
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb','package.json') }}-${{ hashFiles('**/*.{js,ts,jsx,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb','package.json') }}-

      - name: Install
        run: bun install

      - name: Build
        run: bunx --bun build ./index.tsx --outdir ./out

      - name: Upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
